CREATE TABLE Telefone (
	TEL_ID SERIAL PRIMARY KEY,
	TEL_NUMERO INT
)

CREATE TABLE Pessoa (
	PES_ID SERIAL PRIMARY KEY,
	TEL_ID INT NOT NULL,
	PES_NOME VARCHAR(40) NOT NULL
)

ALTER TABLE Pessoa
	ADD CONSTRAINT FK_PESSOA_TELEFONE FOREIGN KEY(TEL_ID) REFERENCES Telefone(TEL_ID)
	
CREATE TABLE Contato (
	CON_ID SERIAL PRIMARY KEY,
	PES_ID INT NOT NULL,
	CON_DATA DATE NOT NULL
)

ALTER TABLE Contato 
	ADD CONSTRAINT FK_CONTATO_PESSOA FOREIGN KEY(PES_ID) REFERENCES Pessoa(PES_ID)
	
